config/routes.rb
Rails.application.routes.draw do
  resources :cabs
  resources :customers
  root 'cabs#index'
  namespace :api , :defaults => { :format => 'json' } do
    resources :cabs do
      collection do
        put 'call_cab'
        put 'end_ride'
      end
    end
  end

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token

private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

end

app/models/cab.rb
class Cab < ActiveRecord::Base
  belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :cab
end

app/controllers/api/cabs_controller.rb
class Api::CabsController < ApplicationController
   # http_basic_authenticate_with name: "admin", password: "secret"
   before_action :set_cab, only: [:show, :edit, :update, :destroy]
   before_filter :restrict_access
  def index
    @cab = Cab.all
    respond_to do |format|
      format.json { render json: @cab }
      format.xml { render xml: @cab }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @cab }
      format.xml { render xml: @cab }
    end
  end

  # def create
  #   @cab = Cab.new(cab_params)
  #   respond_to do |format|
  #     if @cab.save
  #       format.json { render json: @cab, status: :created }
  #       format.xml { render xml: @cab, status: :created }
  #     else
  #       format.json { render json: @cab.errors, status: :unprocessable_entity }
  #       format.xml { render xml: @cab.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def update
  #   respond_to do |format|
  #     if @cab.update_attributes(cab_params)
  #       format.json { head :no_content, status: :ok }
  #       format.xml { head :no_content, status: :ok }
  #     else
  #       format.json { render json: @cab.errors, status: :unprocessable_entity }
  #       format.xml { render xml: @cab.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def destroy
    respond_to do |format|
      if @cab.destroy
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @cab.errors, status: :unprocessable_entity }
        format.xml { render xml: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  def call_cab
    @customer=Customer.find(params[:cust_id])
    if !(@customer.cab_no).blank?
      render json: {message: "Customer already on the ride"}

    else
      request = @customer.request_type
      @cab = Cab.where(status:"available",cab_type:request)
      if !@cab.blank?
        min_dist = 999999999 # assuming the distance will not be greater than this value
        nearest_cab = 1
        @cab.each do |c|
          dist = ((c.location_x-@customer.location_x)**2 + (c.location_y-@customer.location_y)**2)**1/2
          if dist<min_dist
            min_dist = dist
            nearest_cab = c.id
          end
        end

          if Cab.find(nearest_cab).update(status:"booked",customer_id:params[:cust_id]) && Customer.find(params[:cust_id]).update(cab_no:nearest_cab)
            render json: {message: "Cab Booked Successfully"}

          else
            render json: {message: "ERROR"}
          end
      else
        render json: {message: "NO Cabs Available"}
      end
    end
  end

  def end_ride
    @customer = Customer.find(params[:cust_id])
    if !(@customer.cab_no).blank?
      Cab.find(@customer.cab_no).update(status:"available",customer_id:nil,location_x:@customer.destination_x,location_y:@customer.destination_y)
      Customer.find(params[:cust_id]).update(cab_no:nil)
      render json: {message: "Ride Ended Successfully"}
    else
      render json: {message: "Customer is not on the ride"}
    end
  end

  private
    def restrict_access
      api_key = ApiKey.find_by_access_token(params[:access_token])
      head :unauthorized unless api_key
    end

    def set_cab
      @cab = Cab.find(params[:id])
    end

    def cab_params
      params.require(:cab).permit!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/cabs_controller.rb
class CabsController < ApplicationController
  before_action :set_cab, only: [:show, :edit, :update, :destroy]

  # GET /cabs
  # GET /cabs.json
  def index
    @cabs = Cab.all
  end

  # GET /cabs/1
  # GET /cabs/1.json
  def show
  end

  # GET /cabs/new
  def new
    @cab = Cab.new
  end

  # GET /cabs/1/edit
  def edit
  end

  # POST /cabs
  # POST /cabs.json
  def create
    @cab = Cab.new(cab_params)

    respond_to do |format|
      if @cab.save
        format.html { redirect_to @cab, notice: 'Cab was successfully created.' }
        format.json { render :show, status: :created, location: @cab }
      else
        format.html { render :new }
        format.json { render json: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabs/1
  # PATCH/PUT /cabs/1.json
  def update
    respond_to do |format|
      if @cab.update(cab_params)
        format.html { redirect_to @cab, notice: 'Cab was successfully updated.' }
        format.json { render :show, status: :ok, location: @cab }
      else
        format.html { render :edit }
        format.json { render json: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabs/1
  # DELETE /cabs/1.json
  def destroy
    @cab.destroy
    respond_to do |format|
      format.html { redirect_to cabs_url, notice: 'Cab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cab
      @cab = Cab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cab_params
      params.require(:cab).permit(:cab_type, :location_x, :location_y, :status)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :location_x, :location_y, :destination_x, :destination_y, :request_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cabs_helper.rb
module CabsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/cabs/_form.html.erb
<%= form_for(@cab) do |f| %>
  <% if @cab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cab.errors.count, "error") %> prohibited this cab from being saved:</h2>

      <ul>
      <% @cab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cab_type %><br>
    <%= f.text_field :cab_type %>
  </div>
  <div class="field">
    <%= f.label :location_x %><br>
    <%= f.number_field :location_x %>
  </div>
  <div class="field">
    <%= f.label :location_y %><br>
    <%= f.number_field :location_y %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cabs/edit.html.erb
<h1>Editing Cab</h1>

<%= render 'form' %>

<%= link_to 'Show', @cab %> |
<%= link_to 'Back', cabs_path %>

app/views/cabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cabs</h1>

<table>
  <thead>
    <tr>
      <th>Cab Type</th>
      <th>Location x</th>
      <th>Location y</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cabs.each do |cab| %>
      <tr>
        <td><%= cab.cab_type %></td>
        <td><%= cab.location_x %></td>
        <td><%= cab.location_y %></td>
        <td><%= cab.status %></td>
        <td><%= link_to 'Show', cab %></td>
        <td><%= link_to 'Edit', edit_cab_path(cab) %></td>
        <td><%= link_to 'Destroy', cab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cab', new_cab_path %>

app/views/cabs/new.html.erb
<h1>New Cab</h1>

<%= render 'form' %>

<%= link_to 'Back', cabs_path %>

app/views/cabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @cab.cab_type %>
</p>

<p>
  <strong>Location x:</strong>
  <%= @cab.location_x %>
</p>

<p>
  <strong>Location y:</strong>
  <%= @cab.location_y %>
</p>

<p>
  <strong>Status:</strong>
  <%= @cab.status %>
</p>

<%= link_to 'Edit', edit_cab_path(@cab) %> |
<%= link_to 'Back', cabs_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location_x %><br>
    <%= f.number_field :location_x %>
  </div>
  <div class="field">
    <%= f.label :location_y %><br>
    <%= f.number_field :location_y %>
  </div>
  <div class="field">
    <%= f.label :destination_x %><br>
    <%= f.number_field :destination_x %>
  </div>
  <div class="field">
    <%= f.label :destination_y %><br>
    <%= f.number_field :destination_y %>
  </div>
  <div class="field">
    <%= f.label :request_type %><br>
    <%= f.text_field :request_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location x</th>
      <th>Location y</th>
      <th>Destination x</th>
      <th>Destination y</th>
      <th>Request type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.location_x %></td>
        <td><%= customer.location_y %></td>
        <td><%= customer.destination_x %></td>
        <td><%= customer.destination_y %></td>
        <td><%= customer.request_type %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Location x:</strong>
  <%= @customer.location_x %>
</p>

<p>
  <strong>Location y:</strong>
  <%= @customer.location_y %>
</p>

<p>
  <strong>Destination x:</strong>
  <%= @customer.destination_x %>
</p>

<p>
  <strong>Destination y:</strong>
  <%= @customer.destination_y %>
</p>

<p>
  <strong>Request type:</strong>
  <%= @customer.request_type %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fuber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>